api_demo/config/routes.rb
ApiDemo::Application.routes.draw do
  get "users/index"
  resources :oauth_clients
  resources :users, :defaults => { :format => 'xml' }
  match '/oauth/test_request',  :to => 'oauth#test_request', via: [:get,:post] , :as => :test_request
  match '/oauth/token',         :to => 'oauth#token', via: [:get,:post] ,        :as => :token
  match '/oauth/access_token',  :to => 'oauth#access_token', via: [:get,:post] , :as => :access_token
  match '/oauth/request_token', :to => 'oauth#request_token',via: [:get,:post] , :as => :request_token
  match '/oauth/authorize',     :to => 'oauth#authorize',   via: [:get,:post] ,  :as => :authorize
  match '/oauth',               :to => 'oauth#index',       via: [:get,:post] ,  :as => :oauth
  devise_for :users

  root 'oauth_clients#index'
  namespace :api do
    namespace :v1 do
      match "data" => "data#show", via: [:get]
    end
  end

end

api_demo/app/controllers/oauth_controller.rb
require 'oauth/controllers/provider_controller'
class OauthController < ApplicationController
  include OAuth::Controllers::ProviderController
  alias :login_required :authenticate_user!
  protected
  # Override this to match your authorization page form
  # It currently expects a checkbox called authorize
  # def user_authorizes_token?
  #   params[:authorize] == '1'
  # end

  # should authenticate and return a user if valid password.
  # This example should work with most Authlogic or Devise. Uncomment it
  # def authenticate_user(username,password)
  #   user = User.find_by_email params[:username]
  #   if user && user.valid_password?(params[:password])
  #     user
  #   else
  #     nil
  #   end
  # end

end

api_demo/app/views/oauth/authorize.html.erb
<h1>Authorize access to your account</h1>
<p>Would you like to authorize <%= link_to @token.client_application.name,@token.client_application.url %> (<%= link_to @token.client_application.url,@token.client_application.url %>) to access your account?</p>
<%= form_tag authorize_url do %>
  <%= hidden_field_tag "oauth_token", @token.token %>
  <%- if params[:oauth_callback] -%>
  <%= hidden_field_tag "oauth_callback", params[:oauth_callback] %>
<%- end -%>
<p>
  <%= check_box_tag 'authorize' %> authorize access
</p>
<p>
  <%= submit_tag %>
</p>
<% end %>

api_demo/app/views/oauth/authorize_failure.html.erb
<h1>You have disallowed this request</h1>

api_demo/app/views/oauth/authorize_success.html.erb
<h1>You have allowed this request</h1>

api_demo/app/views/oauth/oauth2_authorize.html.erb
<h1>Authorize access to your account</h1>
<p>Would you like to authorize <%= link_to @client_application.name,@client_application.url %> (<%= link_to @client_application.url,@client_application.url %>) to access your account?</p>

<%= form_tag authorize_url do %>
  <%= hidden_field_tag "response_type", params[:response_type]%>
  <%= hidden_field_tag "client_id", params[:client_id]%>
  <%= hidden_field_tag "redirect_uri", params[:redirect_uri]%>
  <%= hidden_field_tag "state", params[:state]%>
  <%= hidden_field_tag "scope", params[:scope]%>

<p>
  <%= check_box_tag 'authorize' %> authorize access
</p>
<p>
  <%= submit_tag %>
</p>
<% end %>